version: 2

sphinx:
  configuration: docs/conf.py

build:
  image: latest

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
  system_packages: true
